version: '3.8'

services:
  # Backend API
  backend:
    build: ./backend
    container_name: subtrack-backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    networks:
      - subtrack-network

  # PostgreSQL database
  postgres:
    image: postgres:14-alpine
    container_name: subtrack-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=subtrack
      - POSTGRES_PASSWORD=subtrack
      - POSTGRES_DB=subtrack
    networks:
      - subtrack-network

  # Notification scheduler service
  scheduler:
    build: ./backend
    container_name: subtrack-scheduler
    restart: always
    command: python scripts/notification_scheduler.py
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - backend
    networks:
      - subtrack-network

volumes:
  postgres_data:

networks:
  subtrack-network:
    driver: bridge